server:
  port: 8200
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wword?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
      # password:
logging:
  file:
    name: logs/WWord.log
  level:
    io.github.cnsukidayo: info

mybatis:
  type-aliases-package: io.github.cnsukidayo.wword.pojo
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

wword:
  resource-locations: D:/Program/Java Project/WWord/wwordResources/