server:
  port: 8201
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

# spring相关配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wword?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  data:
    redis:
      host: localhost
      port: 6379
      # password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      add-mappings: true
  # springcloud相关配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 日志相关配置
logging:
  file:
    path: logs/core/
  level:
    io.github.cnsukidayo: info

#mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  #  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.cnsukidayo.wword.model.entity

# springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    version: v0.0.1
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'user'
#      display-name: "用户端接口"
#      packages-to-scan: io.github.cnsukidayo.wword.controller.u
# knife4j的增强配置,不需要增强可以不配
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: default
      display-name: 用户服务
      packages-to-scan:
        - io.github.cnsukidayo.wword.core.controller


knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false

# 自定义配置
wword:
  resource-locations: D:/Program/Java Project/WWord/wwordResources/
