server:
  port: 8200
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: classpath:ssl/httpsKey.p12
    key-store-password: abc123456789
    key-store-type: PKCS12
    key-alias: wword
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wword?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
      # password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  file:
    name: logs/WWord.log
  level:
    io.github.cnsukidayo: info

#mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  #  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.cnsukidayo.wword.pojo

# springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    version: v0.0.1
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'user'
#      display-name: "用户端接口"
#      packages-to-scan: io.github.cnsukidayo.wword.controller.u
# knife4j的增强配置,不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

wword:
  resource-locations: D:/Program/Java Project/WWord/wwordResources/