# 服务相关配置
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

# spring相关配置
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      add-mappings: false
  # ES相关配置
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}

# 日志相关配置
logging:
  file:
    path: ${LOGGING_FILE_PATH:${wword.resource-locations}logs/${spring.application.name:service-search}/}
  level:
    io.github.cnsukidayo: info
# 分组API配置
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: search-front
      display-name: 搜索模块-前端
      packages-to-scan:
        - io.github.cnsukidayo.wword.search.controller
    - group: search-cloud
      display-name: 搜索模块-微服务
      packages-to-scan:
        - io.github.cnsukidayo.wword.search.api
knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false

# 自定义配置
wword:
  resource-locations: ${WWORD_RESOURCE_LOCATIONS:~/wwordResources/}