server:
  port: 8200
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: classpath:ssl/httpsKey.p12
    key-store-password: abc123456789
    key-store-type: PKCS12
    key-alias: wword

# spring相关配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      add-mappings: false # 先开启静态资源映射
  # 微服务相关配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启配置
      routes:
#        - id: local-service
#          uri: classpath:/META-INF/resources/
#          predicates:
#            - Path=/doc.html
#        - id: local-service
#          uri: classpath:/META-INF/resources/
#          predicates:
#            - Path=/swagger-ui.html
#        - id: local-service
#          uri: classpath:classpath:/META-INF/resources/webjars/
#          predicates:
#            - Path=/webjars/**
#        - id: local-service
#          uri: classpath:classpath:/ist/
#          predicates:
#            - Path=/static/*,/favicon.ico

        - id: service-core
          uri: lb://service-core
          predicates:
            - Path=/api/u/**
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/api/auth/**
        - id: service-admin
          uri: lb://service-admin
          predicates:
            - Path=/api/admin/**

      httpclient:
        ssl:
          use-insecure-trust-manager: true
  main:
    web-application-type: reactive

# 日志相关配置
logging:
  file:
    path: logs/gateway-service/
  level:
    io.github.cnsukidayo: info

knife4j:
  gateway:
    enabled: true
    strategy: manual # 不要使用服务探测,灵活性太低(可能后序版本会改善)
    routes:
      - name: 权限模块-前端
        service-name: service-auth
        url: /service-auth/v3/api-docs/auth-front
        context-path:
      - name: 权限模块-微服务
        service-name: service-auth
        url: /service-auth/v3/api-docs/auth-cloud
        context-path: /
      - name: 业务模块-前端
        service-name: service-core
        url: /service-core/v3/api-docs/core-front
        context-path: /
      - name: 业务模块-微服务
        service-name: service-core
        url: /service-core/v3/api-docs/core-cloud
        context-path: /
      - name: 管理员模块-前端
        service-name: service-admin
        url: /service-admin/v3/api-docs/admin-front
        context-path: /
# 自定义相关配置
wword:
  # 白名单,不走gateway转发的路径
  exclude-url-patterns:
    - api/auth/user/register
    - api/auth/user/login
    - api/auth/user/refresh/*
  production: false
