# 服务相关配置
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
    key-alias: ${SERVER_SSL_KEY_ALIAS}

# spring相关配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_HOST}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      add-mappings: false
  # 微服务相关配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-core
          uri: lb://service-core
          predicates:
            - Path=/api/u/**
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/api/auth/**
        - id: service-admin
          uri: lb://service-admin
          predicates:
            - Path=/api/admin/**
        - id: service-search
          uri: lb://service-search
          predicates:
            - Path=/api/es/**
        - id: service-third-party
          uri: lb://service-third-party
          predicates:
            - Path=/api/third/party/**
      httpclient:
        ssl:
          use-insecure-trust-manager: true

  main:
    web-application-type: reactive

# 日志相关配置
logging:
  file:
    path: ${LOGGING_FILE_PATH:${wword.resource-locations}logs/${spring.application.name:service-gateway}/}
  level:
    io.github.cnsukidayo: info

# knife4j相关配置
knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: 权限模块-前端
        service-name: service-auth
        url: /service-auth/v3/api-docs/auth-front
        context-path:
      - name: 权限模块-微服务
        service-name: service-auth
        url: /service-auth/v3/api-docs/auth-cloud
        context-path: /

      - name: 业务模块-前端
        service-name: service-core
        url: /service-core/v3/api-docs/core-front
        context-path: /
      - name: 业务模块-微服务
        service-name: service-core
        url: /service-core/v3/api-docs/core-cloud
        context-path: /

      - name: 管理员模块-前端
        service-name: service-admin
        url: /service-admin/v3/api-docs/admin-front
        context-path: /

      - name: 搜索模块-前端
        service-name: service-search
        url: /service-search/v3/api-docs/search-front
        context-path: /
      - name: 搜索模块-微服务
        service-name: service-search
        url: /service-search/v3/api-docs/search-cloud
        context-path: /

      - name: 第三方服务-微服务
        service-name: third-party-cloud
        url: /service-third-party/v3/api-docs/third-party-cloud
        context-path: /
      - name: 第三方服务-前端
        service-name: third-party-front
        url: /third-party-front/v3/api-docs/third-party-front
        context-path: /
# 自定义相关配置
wword:
  # 白名单,不走gateway转发的路径
  exclude-url-patterns:
    - "/api/auth/user/register"
    - "/api/auth/user/login"
    - "/api/auth/user/refresh/*"
    - "/api/**/uncheck/**"
  # 哪些路径走gateway的
  url-patterns:
    - "/api/**"
  # 是否是生产环境
  production: false
  # 静态资源映射规则
  resource-locations: ${WWORD_RESOURCE_LOCATIONS:~/wwordResources/}
