server:
  port: 8200
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: classpath:ssl/httpsKey.p12
    key-store-password: abc123456789
    key-store-type: PKCS12
    key-alias: wword

# spring相关配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      add-mappings: false
  # 微服务相关配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启配置
      routes:
        - id: service-core
          uri: lb://service-core
          predicates:
            - Path=/api/u/**
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/api/auth/**

      httpclient:
        ssl:
          use-insecure-trust-manager: true
  main:
    web-application-type: reactive

# 日志相关配置
logging:
  file:
    path: logs/gateway-service/
  level:
    io.github.cnsukidayo: info
