# 服务相关配置
server:
  port: 8203
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

# spring相关配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  web:
    resources:
      add-mappings: false
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.230.128:7901/wword-auth?serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

# 日志相关配置
logging:
  file:
    path: ${LOGGING_FILE_PATH:${wword.resource-locations}logs/${spring.application.name:service-auth}/}
  level:
    io.github.cnsukidayo: info

#mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: io.github.cnsukidayo.wword.model.entity

# 分组API配置
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: auth-front
      display-name: 权限服务-前端
      packages-to-scan:
        - io.github.cnsukidayo.wword.auth.controller
    - group: auth-cloud
      display-name: 权限服务-微服务
      packages-to-scan:
        - io.github.cnsukidayo.wword.auth.api
knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false

# 自定义配置
wword:
  resource-locations: ${WWORD_RESOURCE_LOCATIONS:~/wwordResources/}
  service-auth:
    max-login-log: 50
