server:
  port: 8202
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wword?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
      # password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # 配置异步执行任务
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
      thread-name-prefix: "async-"
  # 微服务相关配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  file:
    path: logs/admin/
  level:
    io.github.cnsukidayo: info

#mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  #  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.cnsukidayo.wword.model.entity

#springdoc配置
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: admin-front
      display-name: 管理员服务
      packages-to-scan:
        - io.github.cnsukidayo.wword.admin.controller

# knife4j的增强配置,不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false


wword:
  resource-locations: D:/Program/Java Project/WWord/wwordResources/