# 服务相关配置
server:
  port: 8202
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

# spring相关配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.230.128:7901/wword?serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  # 配置异步执行任务
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
      thread-name-prefix: "async-"
  # 微服务相关配置
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 5000
    sentinel:
      transport:
        dashboard: ${SPRING_CLOUD_SENTINEL_TRANSPORT_DASHBOARD}
      datasource:
        nacosTemplate:
          nacos:
            server-addr: ${SPRING_CLOUD_SENTINEL_DATASOURCE_NACOSTEMPLATE_NACOS_SERVER_ADDR}
            username: ${SPRING_CLOUD_SENTINEL_DATASOURCE_NACOSTEMPLATE_NACOS_USERNAME}
            password: ${SPRING_CLOUD_SENTINEL_DATASOURCE_NACOSTEMPLATE_NACOS_PASSWORD}
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            data-type: json

logging:
  file:
    path: ${LOGGING_FILE_PATH:${wword.resource-locations}logs/${spring.application.name:service-admin}/}
  level:
    io.github.cnsukidayo: info

#mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
  type-aliases-package: io.github.cnsukidayo.wword.model.entity

#springdoc配置
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: admin-front
      display-name: 管理员服务
      packages-to-scan:
        - io.github.cnsukidayo.wword.admin.controller

# knife4j的增强配置,不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false

# 自定义配置
wword:
  resource-locations: ${WWORD_RESOURCE_LOCATIONS:~/wwordResources/}